# Generated by Django 3.1.6 on 2021-04-08 03:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='カテゴリー')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='販売元')),
            ],
            options={
                'db_table': 'shop',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='品名')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.category', verbose_name='カテゴリー')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.shop', verbose_name='販売元')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
