# Generated by Django 3.1.2 on 2021-04-12 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='決済日')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='決済した数量')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.products', verbose_name='決済した商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='決済した人')),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.products', verbose_name='カゴに入っている商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='カゴの所有者')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
